# ISpawn By ImMaxxx
# Basic Configs
#
spawnPermission: false
warpPermission: false
onJoinTeleportToSpawn: false
onDeathTeleportToSpawn: true
enablePlayerTeleportSound: true
#
# Sounds
teleportSound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
#
# Particle Config
enableSpawnParticles: true
enableWarpParticles: true
particleName: 'one' # particleType can be 'one' or 'two'
particleType: 'FIREWORKS_SPARK'
particleTypeWarps: 'FIREWORKS_SPARK'
