name: ISpawn
version: 3.9
main: de.immaxxx.ispawn.ISpawn
api-version: 1.13
authors: [ ImMaxxx ]

commands:
  setspawn:
    usage: /setspawn
    description: Sets the Spawn
  spawn:
    usage: /spawn
    description: Teleports a Player to the Spawn
  setwarp:
    usage: /setwarp
    description: Sets a Warp
  removewarp:
    usage: /removewarp
    description: Removes a Warp
  warp:
    usage: /warp
    description: Teleports a Player to a Warp
  isreload:
    aliases: ispawnreload
    usage: /isreload
    description: Reloads the Configs

permissions:
  ispawn.use:
    description: Permission to use /spawn
  ispawn.setspawn:
    description: Permission to use /setspawn
  ispawn.tpother:
    description: Permission to use /spawn <playername>
  ispawn.usewarp:
    description: Permission to use /warp <warpname>
  ispawn.setwarp:
    description: Permission to use /setwarp <warpname>
  ispawn.removewarp:
    description: Permission to use /removewarp <warpname>
  ispawn.reload:
    description: Permission to use /isreload
  ispawn.update:
    description: Get a message when a new update is available