name: ISpawn
version: 3.4
main: de.immaxxx.ispawn.ISpawn
api-version: 1.13
authors: [ ImMaxxx ]

commands:
  setspawn:
    description: Sets the Spawn
    usage: /setspawn
  spawn:
    description: Teleports a Player to the Spawn
    usage: /spawn
  setwarp:
    description: Sets a Warp
    usage: /setwarp
  removewarp:
    description: Removes a Warp
    usage: /removewarp
  warp:
    description: Teleports a Player to a Warp
    usage: /warp
  isreload:
    description: Reloads the Configs
    usage: /isreload

permissions:
  ispawn.use:
    description: Use /spawn
  ispawn.setspawn:
    description: Use /setspawn
  ispawn.tpother:
    description: Use /spawn <playername>
  ispawn.usewarp:
    description: Use /warp <warpname>
  ispawn.setwarp:
    description: Use /setwarp <warpname>
  ispawn.removewarp:
    description: Use /removewarp <warpname>
  ispawn.reload:
    description: Use /isreload